package text

const TitleAskForProduct = "Thông tin sản phẩm"
const TitleOtherProduct = "Xem sản phẩm khác"
const TitleAskForPromotion = "Thông tin khuyến mãi"
const TitleAskForSupport = "Nhân viên trợ giúp"
const TitlePlaceOrder = "Đặt hàng"
const TitleBackOrder = "Đặt trước"
const TitleInStockNotification = "Nhận tin khi có hàng"
const TitleChangeInformation = "Thay đổi"
const TitleAcceptOrder = "Gửi đi"
const TitleChangeName = "Tên"
const TitleChangePhone = "Số điện thoại"
const TitleChangeProduct = "Sản phẩm"
const TitleChangeColor = "Màu"
const TitleChangeShop = "Shop lấy hàng"
const TitleInstallmentPay = "Trả góp"
const TitleWholePay = "Trả thẳng"
const TitlePickupStore = "Nhận hàng tại shop"
const TitleHomeDelivery = "Nhận hàng tại nhà"
const TitleSelect = "Chọn shop này"

const PayloadAskForProduct = "fptshop_product_information"
const PayloadAskForPromotion = "fptshop_promotion_information"
const PayloadAskForSupport = "fptshop_support"
const PayloadChangeName = "fptshop_update_name"
const PayloadChangePhone = "fptshop_update_phone"
const PayloadChangeInformation = "fptshop_change_information"
const PayloadChangeColor = "fptshop_change_color"
const PayloadChangeShop = "fptshop_change_shop"
const PayloadAccepOrder = "fptshop_accept_order"
const PayloadInstallmentPay = "fptshop_installment_pay"
const PayloadWholePay = "fptshop_whole_pay"
const PayloadPickupStore = "fptshop_pickup_store"
const PayloadHomeDelivery = "fptshop_home_delivery"
